### ISSUE TITLE
Social message response

### ISSUE THREAD

**Issue by thenewguy** [shacker/django-todo#102]
Could social messaging be integrated into this app so that it could be used as a central source to handle emails / facebook messages / etc?

**Comment by shacker** [comment]
Hi @thenewguy I think that is out of scope for this app. Apps should do one thing and do them well. There are many ways to integrate social media services into your project, and those should be accomplished either by writing them or by installing other apps at the project level. Unless you have some specific idea of how social media and todo lists go together? (I honestly can't think of what the functional overlap might be).

**Comment by thenewguy** [comment]
Fair enough. I thought this could be used as a ticketing system where
multiple people could handle and respond.

The email system appears to have receivers and senders.

I was wondering if this system could be extended to support other receivers
and senders. But just as a generally good fit. For example, Facebook (or
other social media platforms where the pubic can comment). People submit a
question via Facebook and the question is routed to this system. Then the
staff response is posted back via out bound messaging.

I've only briefly inspected this app. But I am looking for something that
will centralize question and response tasks so only one system needs to be
learned so that it is easier to get knowledgeable staff responding to
multiple platforms.

Did I miss the mark on what this system provides?

**Comment by thenewguy** [comment]
To clarify, not so much about the social aspect as in talking to my friends. But adding another ways to ingest messages that are tagged and assigned for action.  I.e. customer submits question on Facebook about pricing -> assigned to sales. Customer submits question about how to fix something he purchased -> assigned to tech support.

**Comment by shacker** [comment]
I'm sorry @thenewguy , but I'm just not seeing it. This seems like a really awkward workflow to me. I was very reluctant to allow the pull request for the email integration that's in place now, and this seems much farther afield. Plus, how would django-todo monitor parts of social sites for messages to ingest? The API work would be super hairy. And not all posts should be made into todo items, etc. I just think there's close to zero demand out there for a feature like this. Tell you what - if you want to write a plugin architecture for django-todo, get that accepted and merged, then you can write a system like this as a plugin. But I predict it's going to take a TON of code to make this work as described, and I don't want to weigh down the current codebase with something that I think fewer than 1% of users can use. 

Thanks for the proposal though.
