### ISSUE TITLE
Login Loop

### ISSUE THREAD

**Issue by MKatereggaExigent** [shacker/django-todo#108]
Good day,

I am trying to integrate the Django-to-do awesome package in my site following the step by step installation  guide at https://github.com/shacker/django-todo but I am stuck in an infinite loop.

**When I login and click on either "Todo Lists" or "My Tasks" I get redirected to: http://127.0.0.1:8000/dashboard/login/?next=/todo/**

**However, when I login I return to the home page without seeing and todo or tasks, and when I click either tabs again, the loop continues. Does anyone knows what the issue is?**

Here is my urls:

urlpatterns = [
    url(r"^dashboard/", include("django.contrib.auth.urls")),
    url(r"^dashboard/", dashboard, name="dashboard"),
    url(r"^$", dashboard, name="home"),
    url(r"^login/", user_login, name="user_login"),
    url(r"^logout/", user_logout, name="user_logout"),
    url(r"^register/", user_register, name="user_register"),
    url(r'^todo/', include('todo.urls', namespace="todo")),
]

Below is the structure of my project:

D:.
│   db.sqlite3
│   debug.log
│   manage.py
│
├───ticketing
│   │   asgi.py
│   │   settings.py
│   │   urls.py
│   │   wsgi.py
│   │   __init__.py
│   │
│   └───__pycache__
│           settings.cpython-38.pyc
│           urls.cpython-38.pyc
│           wsgi.cpython-38.pyc
│           __init__.cpython-38.pyc
│
└───users
    │   admin.py
    │   apps.py
    │   forms.py
    │   models.py
    │   tests.py
    │   urls.py
    │   views.py
    │   __init__.py
    │
    ├───migrations
    │       __init__.py
    │
    ├───static
    │   ├───css
    │   │       bootstrap-fluid-adj.css
    │   │       bootstrap-responsive.css
    │   │       bootstrap-responsive.min.css
    │   │       bootstrap.css
    │   │       bootstrap.min.css
    │   │
    │   ├───img
    │   │       glyphicons-halflings-white.png
    │   │       glyphicons-halflings.png
    │   │
    │   └───js
    │           bootstrap.js
    │           bootstrap.min.js
    │           jquery-3.5.1.js
    │
    └───templates
        │   base.html
        │
        ├───registration
        │       login.html
        │       password_change_done.html
        │       password_change_form.html
        │       password_reset_complete.html
        │       password_reset_confirm.html
        │       password_reset_done.html
        │       password_reset_email.html
        │       password_reset_form.html
        │
        └───users
                dashboard.html
                forms.py
                register.html

**Comment by shacker** [comment]
At the top of your urls.py you've defined the same identical dashboard path twice, and mapped both to django's login system. So once you log in, you're redirected to the dashboard, and your mapping says the dashboard should route to the login system. Remove the first definition of the dashboard path.

**Comment by MKatereggaExigent** [comment]
Thank you @shacker  for the response. When I take the first out then I am unable to use the decorator `@login_required` in `views.py`. I was meant to post yesterday that I resolved the issue. My problem was not having created at least a group with a user as you indicate in the Overview on the Installation page. Thank you very much, this is a great application indeed!!!!
