### ISSUE TITLE
Please do docker-compose

### ISSUE THREAD

**Issue by inakhai** [shacker/django-todo#132]
Dear Shacker, Could you please create docker?

**Comment by shacker** [comment]
@inakhai What would be the advantage? Django has re-usable apps and python has virtualenv so we don't need overly complicated systems like Docker. I didn't even realize re-usable apps could be Dockerized. Can you describe the use case?

**Comment by datatalking** [comment]
@inakhai There are a few cases where docker can be helpful but its more appropriate for larger scaleable application. The djanto-todo is generally more thought of as a small application that while it is growing in popularity its not a larger scaling project.

Why do you feel it is appropriate or advantageous?

https://semaphoreci.com/community/tutorials/dockerizing-a-python-django-web-application
https://www.quora.com/Why-would-one-use-Docker-and-Django-in-the-same-project

**Comment by shacker** [comment]
I think we're miscommunicating. I understand why would one would Dockerize an entire Django project - so that it can be deployed identically on any server or operating system. One generally chooses between virtualenvs and Docker. What I don't understand is why anyone would Dockerize something like Django-todo, which is essentially a library, not a web application. 

Are there examples of other Django reusable apps that are Dockerized? I can't even imagine how that would be used!

**Comment by datatalking** [comment]
We are looking at using django todo as a webapp and hosting it as a private vpc on aws so having a docker setup would help for redundancy. Its something I've had to think about, still in process but we are looking into a web app for multi location users.

**Comment by shacker** [comment]
@datatalking Maybe what you are looking for is a dockerfied version of [GTD](https://github.com/shacker/gtd), which is a reference example of how to make a Django app that includes Django-todo? I can see how it would make sense to Dockerize GTD which is a web application. I don't understand how it makes sense to Dockerize this Django-todo library, which is NOT a web application.

**Comment by datatalking** [comment]
@shacker dockerized web app is what i mean, I've been putting a few apps in Docker and enjoying the process. Do you know of others that have already done this or would this be something feasible we could look at adding?

**Comment by shacker** [comment]
@datatalking Sure, you can open a parallel ticket on the GTD project  - that is a web app. But it doesn't make any sense in this repo. However, if you do open a ticket over there, will you be willing to do the work? I don't have the free time or the Docker expertise.

**Comment by shacker** [comment]
Closing wrt my comment above - feel free to open a PR in the GTD repo where something like this belongs.
