### ISSUE TITLE
Demo `500: Hard Crash` when entering comments

### ISSUE THREAD

**Issue by xtiansimon** [shacker/django-todo#134]
`500: Hard Crash: Something's gone dreadfully wrong. We're on it.`

I created a list and toyed with adding items as `staffer`, and then logging out and back in as `user1`--tried to flip all the switches and push all the buttons. During the demo I has several crashes, and most predictably when entering comments.

Is there a known issue with the server, or with the project which may cause this?

**Comment by shacker** [comment]
@xtiansimon From logs, it looks like you might have been using the site right when the db was being refreshed. Sorry about that. Can you reproduce the issue?  Thanks.

**Comment by shacker** [comment]
No response from the OP on this. I'll try to make the site resilient during db downtimes in the future. Closing.
