### ISSUE TITLE
manage.py is missing

### ISSUE THREAD

**Issue by rshn-dev** [shacker/django-todo#136]
I tried following the https://django-todo.readthedocs.io/en/latest/ and after running pip install django-todo and after running python manage.py runserver, it is giving error "can't open file 'E:\django-todo\manage.py': [Errno 2] No such file or director". There is no file named manage.py . Please suggest.

**Comment by shacker** [comment]
@rshn-dev I think you are misunderstanding what this project is. It is not a Django *project*, it's a Django *app* that you install into *your* project. It's just a python dependency like any other dozens of dependencies your project relies on (take a closer look at the docs). 

See the related gtd project if you're looking for a runnable website.
