### ISSUE TITLE
python3 manage.py migrate todo: multiple exception types must be parenthesized

### ISSUE THREAD

**Issue by nhondong** [shacker/django-todo#138]
Environment:
Ubuntu 22.04 with python 3.10
After adding todo and executing: python3 manage.py migrate todo i get:

File "/home/nhondong/.local/lib/python3.10/site-packages/todo/__init__.py", line 67
    except subprocess.CalledProcessError, e:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

**Comment by shacker** [comment]
@nhondong Thank you, I'll take care of this shortly.

**Comment by shacker** [comment]
@nhondong Something doesn't make sense here. Your report mentions `/site-packages/todo/init.py", line 67` but [here](https://github.com/shacker/django-todo/blob/master/todo/__init__.py) is that module. As you can see, it only goes to like 19. And there is no reference to `subprocess` in the whole codebase. 

I can only conclude that you are working with someone else's repackaged and modified version of todo. Sorry, I can't help with this!
