### ISSUE TITLE
Django 1.8.2 warning and error in todo model

### ISSUE THREAD

**Issue by leonwiskie** [shacker/django-todo#22]
Juist some pointers easy to fix but juist in case you run in to them:

ERRORS:
todo.Item.created_date: (fields.E160) The options auto_now, auto_now_add, and default are mutually exclusive. Only one of these options may be present.

WARNINGS:
todo.Item.priority: (fields.W122) 'max_length' is ignored when used with IntegerField
	HINT: Remove 'max_length' from field

**Comment by shacker** [comment]
Thanks for the report - I'll get these taken care of soon (pull requests welcome).

**Comment by shacker** [comment]
Fixed, thanks.
