### ISSUE TITLE
Release version 1.5 to fix SystemCheckError in Item model

### ISSUE THREAD

**Issue by bittner** [shacker/django-todo#23]
For some reason I get a SystemCheckError when I run `python manage.py check` (was `validate` until Django 1.7) on a project using django-todo with Django 1.8:
``` Bash
SystemCheckError: System check identified some issues:

ERRORS:
todo.Item.created_date: (fields.E160) The options auto_now, auto_now_add, and default are mutually exclusive. Only one of these options may be present.
```
The field provoking the error is [created_date](https://github.com/shacker/django-todo/blob/master/todo/models.py#L45) in the `Item` model.

**Comment by bittner** [comment]
This is obviously a duplicate of #22.

Would be nice if we could release version 1.5 that fixes the issue. Is this doable?

**Comment by shacker** [comment]
Odd - I thought this was fixed. I'm very booked for the next 10 days but can look it after that. In the meantime it should be an easy fix if you don't mind digging into the model code (pull request welcome!) Sorry about this.

**Comment by bittner** [comment]
That *is* fixed. But not in the release version (1.4 on PyPI). We need to release the changes in the repository to PyPI as a new version.

If you don't mind I can do the release. I think I do have the privileges to do so.

**Comment by bittner** [comment]
Looks like this issue [is fixed](https://pypi.python.org/pypi/django-todo).

Odd that I didn't close the issue after uploading the package to PyPI in September. I apologize.

**Comment by shacker** [comment]
Thanks again!
