### ISSUE TITLE
Is `MissingSuperuserException` really needed?

### ISSUE THREAD

**Issue by bittner** [shacker/django-todo#25]
When installing `django-todo` with a project you can't run the project, because the package throws a `MissingSuperuserException`:
```
MissingSuperuserException at /
django-todo requires at least one superuser in the database
```
The exception comes from the [settings module](https://github.com/shacker/django-todo/blob/master/todo/settings.py#L11).

Is this really needed? This way you can't run a project that has no use for a superuser or manages all administration tasks from the command line. If there are no compelling reasons for having to have a superuser there should be a warning instead of a hard exception, if any.

**Comment by shacker** [comment]
Hmm, I wonder how common this scenario is. In 10 years of Django dev and dozens of projects, I have never worked on a project that lacked a superuser. The limitation was put there because there was no way to bootstrap a new project with todo as its only app. I guess I would argue that there's always a compelling reason to have a superuser (this use case is just such a reason). And there's no real downside to creating one if you don't have one already. 

In the absence of a superuser, who should we allow to create new lists? Everyone?

**Comment by bittner** [comment]
I would say, if I create a new list it's my personal list. My personal TODO list.

If I want to do more, use the app in an organization, I go ahead and create a superuser on the command line, then I create more users  (if my site doesn't support self-registration), user groups and lists.

I feel requiring a superuser (in an app) is an arbitrary limitation. It's not necessary, or at least it shouldn't be necessary. Specifically with `django-todo`, I would first and foremost use the app for my personal TODO list(s). Why should I create a superuser for that?

## Django and superuser practice

I agree that one of the first things most Django developers do in greenfield projects is create a superuser. I guess the majority of them doesn't even know that this isn't necessary for running Django projects. But this doesn't mean it's required to do it.

The only real advantage (and difference compared to a, say, Windows Administrator or Unix root user) of a Django superuser is that it is allowed to access the Admin. Otherwise I'm sure using more than an unprivileged user in Django would be considered as "bad practice" by the Django Project.

Other opinions allowed, of course.

**Comment by shacker** [comment]
I misspoke - it's already the case that people can create their own lists. The MissingSuperUser raise was put in place just to support the DEFAULT_ASSIGNEE for public tickets. But you're right - there's no reason that assignee has to be a superuser - that was just me assuming that all projects have one. I'll fix that.

**Comment by bittner** [comment]
Does a task have to be assigned to a user? Can't there be unassigned tasks? By default, maybe?

I know that in IT we put things we know that need to be done into a backlog, without specifying who should deal with that. It's just important that the task is created, so that the information is not lost.

Whoever starts to work on it will assign her-/himself to it ("pull" in an agile environment), whoever wants someone else to work on the task will assign that person to the task (in a traditional, managed environment).

**Comment by shacker** [comment]
Now just requiring default_assignee in settings when using the anon ticket submission feature, not superuser for all.

**Comment by shacker** [comment]
You make a very good point re: unassigned tasks. Let me think about that a bit.

**Comment by shacker** [comment]
Unassigned tasks are now supported in django-todo.
