### ISSUE TITLE
Slug names conflict

### ISSUE THREAD

**Issue by renegadeofunk** [shacker/django-todo#30]
Hello,

I'm using this as a helpdesk/ticketing system and I noticed that if two lists in different groups have the same name then they generate the same slug name and a later get() will get that "more than one result" error. Line 94 in views.py.

I was able to fix it for myself by manually updating the slug names in the database to be different from each other.

Thanks!

**Comment by shacker** [comment]
Thanks for the report! This has been fixed in 9c3000f572d4b6749e9eaee400f8d04a0b61f45f
