### ISSUE TITLE
Attachment support

### ISSUE THREAD

**Issue by adamarla** [shacker/django-todo#39]
Have you considered adding support for attaching documents/images to tickets? 
We like the library but attachment support is a non-negotiable for our users. Would be happy to add a feature that provides this too if you can help with some direction. Thanks!

**Comment by shacker** [comment]
Interesting idea! In all these years, this is the first time I've had this feature request. I would be very open to a pull request for this. Definitely write it in Python3/Django 2+. Please make sure it's an optional to enable via settings, following the pattern of existing settings for django-todo. And if it all possible, please add a test or tests. And document the implementation for anyone who wants to enable it. Please use Django's "Storages" system for handling the uploads. 

We are assuming Bootstrap for the base implementation, so if you want to add any JS functionality, please tap into that (try not to introduce any additional JS requirements, but ping me if you feel you need to).

**Comment by shacker** [comment]
@adamarla Are you still interested in contributing this feature? Would anyone else watching care to contribute towards it?

**Comment by adamarla** [comment]
Sorry, not at the moment, we ended up not using this library.

**Comment by shacker** [comment]
@adamarla OK, I'll add it to the todo list as it's a good idea, and will leave this issue open in case anyone wants to pick it up.

**Comment by swamybachu** [comment]
Anyone watching has a update on this.

**Comment by shacker** [comment]
No one has contributed code for this yet, but it shouldn't be difficult and seems like a good idea. I'll make it the next priority if no one else jumps in with a PR.

**Comment by shacker** [comment]
Hi @adamarla @swamybachu - File attachment support is now enabled and released in django-todo 2.4.x , which is available on pypi and running on django-todo.org (feel free to test it there).

Let me know what you think! Closing this issue, but comments or contributions welcome.
