### ISSUE TITLE
MySQL support broken

### ISSUE THREAD

**Issue by multun** [shacker/django-todo#56]
https://stackoverflow.com/questions/33211540/is-there-anyway-to-create-unique-textfield-in-django-with-mysql-db-backend

A unique constraint can't be expressed because of mysql being half-assed. The only fix I can think of is the following:

 - modify the existing migration to add a charfield instead, if a mysql backend is used
 - add a new migration changing the textfield to a charfield if mysql isn't used

**Comment by shacker** [comment]
Geez, that's hacky, though it would work. Is there anything else that can be keyed to? And what do you think of the hashing solution proposed in that SO response?

Can you link to where in the code this is happening?

**Comment by multun** [comment]
The drama happens [here](https://github.com/shacker/django-todo/blob/master/todo/models.py#L139). Unfortunately, the issue affects all users, not only mail tracker users (the field is added even if it isn't used).

**Comment by shacker** [comment]
OK, practicalities... 

The max length of a MySQL CharField is 255 chars.
Googling for message-id examples, I learn that the theoretical max length is 995 chars.
But the longest example of a REAL one I can find in the wild is 111 chars.
I'm sure it's possible for longer ones to occur, but how likely? 

Wikipedia: "A common technique used by many message systems is to use a time and date stamp along with the local host's domain name, e.g., 950124.162336@example.com"

IOTW if you took the incoming message-id and truncated to 255 chars, the likelihood of ever encountering a duplicate error is vanishingly close to zero. It's not a theoretically perfect solution, but in practice? I seriously doubt any user would ever encounter a problem. 

So... converting to a CharField and truncating the inbound to 255 seems preferable to these messy migrations, I think. 

I haven't yet pushed to pypi so users of this landed PR are very few. I recommend biting the bullet and making this change.

**Comment by multun** [comment]
> So... converting to a CharField and truncating the inbound to 255 seems preferable to these messy migrations, I think.

we need to do both ! we can't delete the former migration, as it was already published, but it is failing. So we have to modify it. And we have to create one more to reach the desired state.

**Comment by shacker** [comment]
OK, I agree. Would you mind making a PR for that? Probably the sooner the better.

**Comment by multun** [comment]
Will do

**Comment by shacker** [comment]
How is this coming along? Can I lend a hand?

**Comment by multun** [comment]
@shacker sorry about that x) I'm currently super busy and didn't find enough time to do it

> Can I lend a hand?

Sure !

**Comment by shacker** [comment]
@multun Can you review this PR please? 
https://github.com/shacker/django-todo/pull/57

I can't test it on mysql, but I have done a full / fresh db test with postgres and it seems fine.

Again, I have not yet pushed  to pypi so I think the number of users of this github version is VERY small, and the percentage of those who use mysql is even smaller. IOTW if this isn't perfect for the few mysql users who have previously run the 0008 migration, I'm not overly concerned.

**Comment by shacker** [comment]
And it's green on travis.

**Comment by shacker** [comment]
Wait... does migration 0008 actually refuse to run for mysql users? If so, this PR isn't going to work and we'll have to do surgery on 0008 itself.

**Comment by multun** [comment]
I think 0008 refuses to run on mysql x)

**Comment by shacker** [comment]
Yeah, that kind of sunk in after I posted. OK will re-do this later today.

**Comment by shacker** [comment]
OK, that made it even easier. Just updated with a simple fix for 0008, removal of 0009, and a separate formatting commit. This might trip up anyone who has pulled from github rather than pypi in the past week, but I'm OK with that - let's move on. WDYT?
