### ISSUE TITLE
demo site not working

### ISSUE THREAD

**Issue by Abdisalanvp77** [shacker/django-todo#63]

**Comment by shacker** [comment]
Yeah that was quite an adventure. With the latest 2.3 release we had a migration that failed with postgres. Only then did I realize I was running an older/unsupported postgres version on the demo site. When I tried to upgrade postgres, everything went wrong. Finally realized it was time to create a new droplet on digital ocean which meant re-learning how to set up systemd, gunicorn, nginx, etc. I was super busy at work and the conversion took a couple of evenings. Sorry for the downtime, but all good now (and it's even faster than before).
