### ISSUE TITLE
No todo folder

### ISSUE THREAD

**Issue by swamybachu** [shacker/django-todo#68]
Hi, 
I used pip install django-todo to install the app in my virtual env. 
Then i added the 'todo' to the INSTALLED_APPs in settings.py , and migrated the todo app, and everything. 
After that i ran the server and i am able to get in the admin site( i created a superuser), but i cannot get in the todo app.( i added this in urls.py as well) 
    path('',include ('todo.urls')),

What am i missing.

**Comment by shacker** [comment]
@swamybachu Are you saying that visiting the url `/todo` doesn't work? Do you get 404 or a crash? Or do you mean that you don't know how to add it to your site's navigation? Sorry I need more information.

**Comment by shacker** [comment]
Closing this as there is not enough information in the issue to reproduce or to help the OP. Please re-open if you are still having an issue.
