### ISSUE TITLE
Error migrating

### ISSUE THREAD

**Issue by davestgermain** [shacker/django-todo#73]
I'm trying to install with Django 2.2 and getting this error when migrating:
```ERRORS:
<class 'todo.admin.AttachmentAdmin'>: (admin.E040) ModelAdmin must define "search_fields", because it's referenced by AttachmentAdmin.autocomplete_fields.
common.Comment.commented_by: (fields.E304) Reverse accessor for 'Comment.commented_by' clashes with reverse accessor for 'Comment.author'.
	HINT: Add or change a related_name argument to the definition for 'Comment.commented_by' or 'Comment.author'.
todo.Comment.author: (fields.E304) Reverse accessor for 'Comment.author' clashes with reverse accessor for 'Comment.commented_by'.
	HINT: Add or change a related_name argument to the definition for 'Comment.author' or 'Comment.commented_by'.
```

**Comment by shacker** [comment]
@davestgermain I'm having trouble reproducing this issue. I just upgraded my sample project to Django 2.2.1 and no migrations were required. Then I created a fresh db and migrated it up from scratch - that also went fine. And we haven't seen any other reports of this. Can you tell us anything about your setup that might be unusual?

**Comment by davestgermain** [comment]
@shacker Sorry, this was a false alarm. My project also uses django-crm, which has its own User and Comment models. I think I'll submit a PR against their project to fix the name clashing. But one thing you could change is the `related_name` [on Comment.author](https://github.com/shacker/django-todo/blob/master/todo/models.py#L134). If you don't expect to query for all of an author's comments, I believe you can set it to `related_name='+'`, and then the ORM won't add anything to the user model.

**Comment by shacker** [comment]
Thanks Dave - I've made a separate note of this suggestion and will have a look into it before long.
