### ISSUE TITLE
Settings are ignored

### ISSUE THREAD

**Issue by Fandekasp** [shacker/django-todo#77]
Related issue: #47 
Related code: https://github.com/shacker/django-todo/blob/master/todo/defaults.py#L24

```py
ipdb> settings.TODO_STAFF_ONLY                          
False
ipdb> key                   
'TODO_STAFF_ONLY'
ipdb> getattr(settings, key, False) or hash.get(key)    
True
```

TODO_STAFF_ONLY is always True, and I don't see how it could have ever worked. the first part `getattr(settings, key, False)` evaluate to either True or False, and the second part always evaluates to True...  `False or True` = `True` or `True = True`.

**Comment by shacker** [comment]
Great catch, serves me right for releasing that feature without tests. 
todo 2.4.8 is released with a fix for this issue. And tests!
Thanks.
