### ISSUE TITLE
Requirements: html2text in Readme?

### ISSUE THREAD

**Issue by james1293** [shacker/django-todo#83]
This is super minor, but should `html2text` be listed in the Readme as a requirement? It's used by `tracker_consumer`  (`from todo.mail.consumers import tracker_consumer` as shown [here](https://github.com/shacker/django-todo#mail-tracking)).

**Comment by shacker** [comment]
Thanks, I'll look into it eventually. I don't use that feature in todo, so haven't come across this.

**Comment by shacker** [comment]
It's already / has always been [listed as a dependency](https://github.com/shacker/django-todo/blob/master/Pipfile#L15). It should have been installed automatically when you installed todo.

Closing, but let me know if there was another reason it didn't get installed for you. Maybe you weren't using Pipenv? I don't really accommodate other dependency management systems, but I would entertain the possibility if people had strong opinions on this.
