### ISSUE TITLE
Saving a completed task makes completed=False

### ISSUE THREAD

**Issue by james1293** [shacker/django-todo#84]
1. Create a task.
2. Mark it as complete.
3. Edit the completed task.
4. Save it.
5. The task is now marked incomplete.

AFAICT, step 5 shouldn't happen. Thoughts?

**Comment by shacker** [comment]
Thanks - on break right now, will check into this soon.

**Comment by james1293** [comment]
No rush! :slightly_smiling_face:

**Comment by shacker** [comment]
Sorry for the long delay. This is now fixed in 2.4.9. Thanks for the bug report and PR!
