### ISSUE TITLE
Username and/or Email option

### ISSUE THREAD

**Issue by adux** [shacker/django-todo#88]
I got a request to use this app for a particular project that uses allauth with an email instead of username field. So, just to be clear, there is no user.username or so. This of course creates some issues, none of them too difficult to solve, but there's no django-todo native way to do it. 

Is there already a solution for this particular situation?
Is there a interests for something like this? I could dev a config option.

**Comment by shacker** [comment]
Hi - Not clear why this issue was closed before we'd discussed it. So I don't think allauth has anything to do with your problem - it sounds like you've set up a custom User model that has no username. I didn't even realize that was possible? Can I see your custom User model?

**Comment by adux** [comment]
There weren't many changes need to for it to work so i just made the changes in a fork in a bit of a ugly way :)) and i closed it cause to be honest im not sure many people would use this cause good practice probably just sort of duplicates the email to the username ? 

And your right, it has nothing to do with allauth. 

Here are the main parts of the Custom User model:

`class User(AbstractBaseUser, PermissionsMixin):                                                                                                                                           
 47     # Important                                                                                                                                                                           
 48     email = models.EmailField(_('email address'), unique=True)                                                                                                                            
 49     date_joined = models.DateTimeField(_('date joined'), default=timezone.now)                                                                                                            
 50     is_active = models.BooleanField(_('active'), default=True)                                                                                                                            
 51     is_staff = models.BooleanField(_('staff status'), default=False)                                                                                                                      
...
 72     objects = UserManager()                                                                                                                                                               
 73                                                                                                                                                                                         
 74     USERNAME_FIELD = 'email'                                                                                                                                                              
 75     REQUIRED_FIELDS = []`

`15 class UserManager(BaseUserManager):                                                                                                                                                       
 16     use_in_migrations = True                                                                                                                                                             
 17                                                                                                                                                                                          
 18     ef _create_user(self, email, password, **extra_fields):                                                                                                                              
 19        """                                                                                                                                                                               
 20        Creates and saves a User with the given email and password.                                                                                                                       
 21        """                                                                                                                                                                               
 22        if not email:                                                                                                                                                                     
 23            raise ValueError('The given email must be set')                                                                                                                               
 24        email = self.normalize_email(email)                                                                                                                                               
 25        user = self.model(email=email, **extra_fields)                                                                                                                                    
 26        user.set_password(password)                                                                                                                                                       
 27        user.save(using=self._db)                                                                                                                                                         
 28        return user`

**Comment by shacker** [comment]
Got it. One of these days I'll look into this a bit more - it's possible Django provides some abstraction for "user field" that would make it possible to work if you don't have a username. OTOH, I would imagine that TONS of 3rd party libs would break for you - it's kind of globally assumed that all Django projects have a username. You might find life easier if you just add a username field.

**Comment by shacker** [comment]
Closing this for now. I'm having trouble finding any documentation about this, but I think it is legitimate for a third-party app like this one to assume that there is a populated username field in a running Django system. Even if that system is built to allow email-based logins, it should be populating username with *something* -- otherwise I would expect breakage like this all over the place. IOTW I don't think django-todo is being presumptuous here. If anyone disagrees or finds documentation to the contrary, please leave a comment and I'll re-open this.
