### ISSUE TITLE
Implementing pagination

### ISSUE THREAD

**Issue by Sasa993** [shacker/django-todo#91]
I implemented the pagination into search functionality - and it works great.
But, I'm having some trouble doing that with a list of tasks.
I did everything right in list_detail.py, but the errors keep popping up "'Page' object has no attribute 'filter'"...
Any ideas?

Thank you in advance

**Comment by shacker** [comment]
Hi @Sasa993 - I don't see a pull request or link here, so there's no way to see your code and thus no way anyone can help you! Is this something you're contributing to the project? Where's the Issue and Pull Request?
