### ISSUE TITLE
Not able to add my own path

### ISSUE THREAD

**Issue by Mcflan-7** [shacker/django-todo#92]
Hi,

I tried for several day to make my own function on your app using add_list.py but whenever I want to use it on urls.py, they say that module or function does not exist.

Do you know why ?

Thanks

**Comment by Mcflan-7** [comment]
Any update ? 
Still not able to figure it out.
Thanks

**Comment by shacker** [comment]
@Mcflan-7 You have not shared any code, so I don't really understand how you could expect anyone to begin to be able to help you. 

Are you trying to make a feature enhancement to django-todo? Where is the pull request? 

Share your urls.py, the imports it makes, and the dotted path to your function, maybe we can help you.

**Comment by shacker** [comment]
Closing because I don't understand the question and have not heard back from the OP.
