### ISSUE TITLE
Can not find the key attachment_set for Task Class, but how can task_detail render normally?

### ISSUE THREAD

**Issue by tuhaolam** [shacker/django-todo#94]
I have define another class Audit, hence need to custom my template, when I upload a attachment, but the page can not show the attachment, due to the new class don't have the key attachment_set.
More details can see task_detail.html:
```
{% if attachments_enabled %}
  <div class="card mt-4">
    <h5 class="card-header">
      Attachments
    </h5>
    {{ task.attachment_set.count }} <!--can not find attachment_set for task-->
```

**Comment by shacker** [comment]
Have you proved to yourself that this very task has attachments from the command line?

**Comment by tuhaolam** [comment]
Yes, at last I found that it's a feature of Django about relational database. The model class 'Attachment' uses the filed 'task_id' of 'Task' as foreigne key, and 'task.attachment_set.count' exists, by the same way, we can define another class 'AuditAttachment', uses the filed 'task_id' of 'Audit' as foreigne key, and 'audit.auditattachment_set.count' exists.

**Comment by shacker** [comment]
> Yes, at last I found that it's a feature of Django about relational database

Oh sorry I did not realize you did not know that. Can we close this issue then?
