### ISSUE TITLE
Confirm before delete

### ISSUE THREAD

**Issue by dalinxz** [shacker/django-todo#97]
Hey shacker, incredible work on this lightweight but powerful todo app! Thank you.

I had one suggestion for future improvements, which is to add a confirm before deleting the task. Keep it up, really appreciate the work.

**Comment by shacker** [comment]
Good suggestion @dalinxz . I've retitled this issue and marked it "Good first issue" for anyone who drives by and wants to contribute the feature. Thanks.

**Comment by sum35h** [comment]
Hi @dalinxz , I would like to work on this, if the issue is still open.

**Comment by shacker** [comment]
Sure thing @sum35h - this still needs to be done, and I welcome your pull request any time. Thanks in advance.

**Comment by aaroosh-07** [comment]
@shacker can i take up this issue

**Comment by shacker** [comment]
@sum35h Have you started on this? If not, do you mind of @aaroosh-07 works on it?

**Comment by 1hanzla100** [comment]
@shacker I want to fix this issue. Assign it to me

**Comment by shacker** [comment]
@1hanzla100 I don't assign things here - most OSS projects don't. Either communicate with others in this thread, or just be first with a good pull request!

**Comment by EdgarPrada** [comment]
This improvement is already done. -Shouldn't this be marked as closed? 
Great project. Thanks

**Comment by shacker** [comment]
Thanks @EdgarPrada, right you are. Closing. Glad you enjoy the project!
